# Generated by Django 5.2.6 on 2025-10-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_fooditem_price_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
